### ISSUE TITLE
Svg Rendering is slow, please switch to ttf icons instead

### ISSUE THREAD

**Issue by prateekmedia** [jesusrp98/adwaita_icons#1]
Additional information:
https://pub.dev/packages/icon_font_generator
https://pub.dev/packages/fantasticon_flutter

**Comment by prateekmedia** [comment]
Other icon packs who use these plugins:
[yaru_icons](https://pub.dev/packages/yaru_icons) uses fantasticon_flutter to generate there icon packs.

**Comment by jesusrp98** [comment]
Hey! There's a major issue regarding GTK icons: they're not font-friendly at all.

I spent countless hours trying to format the icons such as the output font would be decent, but as far as I know is almost impossible.

There's also the problem with semi transparent surfaces. As it currently stands, Flutter doesn't support the render of semitransparent characters using a font. So many of the GTK icons could not be used, since they use this feature.

So second best decision was using the original `svg` files, and render them using `fluttter_svg`.

I understand this is an inconvenience for everyone, but I really think creating a font form the GTK icons is not feasible right now.

If you find a possible solution for the problems I listed here I'd be more than happy to collaborate with you.
